import { Fragment } from "react";
import Head from "next/head";

export default function Docs() {
  return (
    <Fragment>
      <Head>
        <title>Example: Introduction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-2 pt-1">
        <h1>Introduction here</h1>
      </div>
    </Fragment>
  );
}
