name: Label PR's

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    # if: github.repository_owner == 'ok2ju'
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
