name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate root Changelog
        id: rootChangelog
        # if: steps.changesets.outputs.published == 'true'
        run: yarn changelog:root

      - name: Push root Changelog
        if: steps.rootChangelog.outcome == 'success'
        env:
          CI_GIT_USERNAME: github-actions[bot]
          CI_GIT_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git config --local user.email "${{ env.CI_GIT_EMAIL }}"
          git config --local user.name "${{ env.CI_GIT_USERNAME }}"

          git checkout -b "root-changelog"
          git add -A
          git commit -m "Release root Changelog"
          git push origin root-changelog
